version: '3'
services:
  db-cats-api:
    image: postgres:12
    restart: always
    ports:
        - 5444:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: cats_api